"""
Module to store constant values, particularly DataFrame column names,
to ensure consistency across the project.
"""

# --- Columns for Modules DataFrame ---
MODULE_ID = 'module_id'
MODULE_CODE = 'module_code'
MODULE_NAME = 'module_name'

# --- Columns for Enriched WLSections DataFrame ---
# WLoad Level
WLOAD_ID = 'wload_id'
WLOAD_NAME = 'wload_name'
# MODULE_ID, MODULE_NAME, MODULE_CODE already defined above
ACADEMIC_TERM_SLOT = 'academic_term_slot'
WLOAD_TYPOLOGIES_NUM_SLOTS = 'wload_typologies_num_slots'
TYPOLOGY_IDS = 'typology_ids'
TYPOLOGY_NAMES = 'typology_names'
WEEKS_IDS = 'week_ids'
WEEKS_START_DATES = 'week_startDates'

# Constants for WLoad Typologies
TYPOLOGY_NUM_SLOTS = "wload_typologies_num_slots"

# WLSession Level
WL_SESSION_ID = 'wl_session_id'
WL_SESSION_NAME = 'wl_session_name'

# WLSSection Level
WLS_SECTION_ID = 'wls_section_id'
WLS_SECTION_NAME = 'wlsSectionName'
WLS_SECTION_NUM_STUDENTS = 'wls_section_num_students'
WLS_SECTION_CONECTOR = 'wlsSectionConnector'
STUDENT_GROUP_IDS = 'studentGroup_ids'
STUDENT_GROUP_NAMES = 'studentGroup_names'
STUDENT_GROUP_STATE = 'studentGroup_active'

# --- Columns for Teachers DataFrame --- (For Merging)
# WLOAD_ID, WLS_SECTION_NAME are already defined or implicitly used
TEACHER_IDS = 'teacher_ids'
TEACHER_NAMES = 'teacher_names'
TEACHER_CODES = 'teacher_codes'
TEACHER_STATE = 'teacher_active'

# --- Default Values ---
DEFAULT_NO_TEACHER_STRING = 'Without_Teacher'

# Default values for teacher data if not found
DEFAULT_TEACHER_IDS = ""
DEFAULT_TEACHER_NAMES = ""
DEFAULT_TEACHER_CODES = ""
DEFAULT_TEACHER_STATE = ""

# --- Output File Constants ---
OUTPUT_RAW_EVENTS_EXCEL_FILENAME = "raw_extracted_events_data.xlsx" 

OUTPUT_VIEWER_EVENTS_EXCEL_FILENAME = "viewer_extracted_events_data.xlsx"
OUTPUT_FILES_DIR = "DATA_PROCESS" # Default directory for all output Excel files 

# --- Columns for Processed Events DataFrame (event_processor.py) ---
# These are keys used in the DataFrame generated by process_raw_events_df
EVENT_ID = 'event_id'
EVENT_NAME = 'event_name'
